# Generated by Django 5.1.2 on 2024-11-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
